use database customer_database;

use schema consumption_zone;


 select * from fact_table;

 //What is the total revenue generated for each product?
 SELECT 
    PRODUCTNAME, 
    SUM(REVENUE) AS TOTAL_REVENUE
FROM CONSUMPTION_ZONE.FACT_TABLE
GROUP BY PRODUCTNAME
ORDER BY TOTAL_REVENUE DESC;
// store  with high profit 
SELECT 
    STATE, 
    SUM(PROFIT) AS TOTAL_PROFIT
FROM CONSUMPTION_ZONE.FACT_TABLE
GROUP BY STATE
ORDER BY TOTAL_PROFIT DESC;
//How many orders were placed each month?
SELECT 
    DATE_TRUNC('MONTH', ORDERDATE) AS MONTH, 
    COUNT(DISTINCT ORDERNUMBER) AS TOTAL_ORDERS
FROM CONSUMPTION_ZONE.FACT_TABLE
GROUP BY MONTH
ORDER BY MONTH;

//Which customer has placed the highest number of orders?
SELECT 
    CONCAT(FIRST_NAME, ' ', LAST_NAME) AS CUSTOMER_NAME, 
    COUNT(DISTINCT ORDERNUMBER) AS TOTAL_ORDERS
FROM CONSUMPTION_ZONE.FACT_TABLE
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 1;
//Which products have been ordered in the highest quantities
SELECT 
    PRODUCTNAME, 
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM CONSUMPTION_ZONE.FACT_TABLE
GROUP BY PRODUCTNAME
ORDER BY TOTAL_QUANTITY DESC;
